version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.4.1"
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          # For some reason, bundle install fails when install the dotenv
          # gem with a permissions issue in tmp. This does not happen
          # if you ssh into the build and run bundle install manually.
          # sudo hacks around the problem for now.
          name: bundle install
          command: sudo bundle install
      - run:
          name: Build and run tests
          command: bundle exec fastlane scan
      - store_test_results:
          path: ~/project/test_output
      - store_artifacts:
          path: ~/project/test_output
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
