version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.4.1"
    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
