version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.4.1"
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: Build and run tests
          command: bundle exec fastlane scan
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
